spring:
  ai:
    azure:
      openai:
        endpoint:
        apiKey:
        region:
        api-version:
        chat:
          options:
            temperature: 1.0
            #max_tokens:
            deployment-name: